name: Feature Request
description: Suggest new case studies or improvements
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have a system to design? We'd love to add it!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added?
      placeholder: Describe your suggestion...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Case Study
        - Architecture Pattern
        - Diagram Improvement
        - Interview Tips
        - Performance Section
        - Other
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: If a new case study, what are the requirements?
      placeholder: |
        Functional:
        - Feature A
        - Feature B
        
        Non-Functional:
        - Scale: X users
    validations:
      required: false

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this valuable?
      placeholder: This is commonly asked in interviews...
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can help write this content
          required: false
